languageCode = "en"
languageName = "English"
weight = 1
title = "suleif's blog"
contentDir = "content/en"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
description = "A blog about security stuff"
dateFormat = "2 January 2006"

  [params.author]
  name = "suleif"
  image = "img/klein.jpg"
  headline = "This is my humble blog about security research."
  bio = "I love complex systems, and I love exploring their internals."

    [[params.author.links]]
    github = "https://github.com/loot01"

    [[params.author.links]]
    x-twitter = "https://twitter.com/proteinpowder00"

    [[params.author.links]]
    linkedin = "https://www.linkedin.com/in/soulaimane-hafid-7638b8286/"

["params.author"]
name = "suleif"
email = "suleif@proton.me"
